using System.ComponentModel.DataAnnotations;

namespace Campsite.Models;
public sealed class Campsite { public int Id { get; set; } public string Name { get; set; } = ""; public string SiteType { get; set; } = ""; public string Description { get; set; } = ""; public decimal NightlyRate { get; set; } public int MaxGuests { get; set; } public bool HasElectric { get; set; } public bool IsActive { get; set; } }
public sealed class Activity { public int Id { get; set; } public string Title { get; set; } = ""; public string Description { get; set; } = ""; public DateTime StartsAt { get; set; } public string Location { get; set; } = ""; }
public sealed class MenuItem { public int Id { get; set; } public string Category { get; set; } = ""; public string Name { get; set; } = ""; public string Description { get; set; } = ""; public decimal Price { get; set; } public bool IsAvailable { get; set; } }
public sealed class Reservation { public int Id { get; set; } public int CampsiteId { get; set; } public string CampsiteName { get; set; } = ""; public int CustomerId { get; set; } public string CustomerName { get; set; } = ""; public string CustomerEmail { get; set; } = ""; public DateOnly CheckIn { get; set; } public DateOnly CheckOut { get; set; } public int Guests { get; set; } public decimal Total { get; set; } public string Status { get; set; } = ""; public string PaymentStatus { get; set; } = ""; public string PaymentMethod { get; set; } = ""; }
public sealed class Customer { public int Id { get; set; } public string Name { get; set; } = ""; public string Email { get; set; } = ""; public string Phone { get; set; } = ""; public DateTime CreatedAt { get; set; } }
public sealed class ThemeSettings { public string Primary { get; set; } = "#245b3a"; public string Forest { get; set; } = "#173c2a"; public string Earth { get; set; } = "#60452f"; public string Sand { get; set; } = "#f5eedc"; public string Ember { get; set; } = "#e77824"; }
public sealed class BookingInput { [Required] public int CampsiteId { get; set; } [Required] public DateOnly? CheckIn { get; set; } [Required] public DateOnly? CheckOut { get; set; } [Range(1, 20)] public int Guests { get; set; } = 2; [Required, StringLength(90)] public string Name { get; set; } = ""; [Required, EmailAddress] public string Email { get; set; } = ""; [Phone] public string Phone { get; set; } = ""; [Required] public string PaymentMethod { get; set; } = "stripe"; }
public sealed class SearchInput { [Required] public DateOnly? CheckIn { get; set; } [Required] public DateOnly? CheckOut { get; set; } [Range(1,20)] public int Guests { get; set; } = 2; }
